/* Auto-generated by cbindgen. Do not edit. */

#ifndef PACKET_ENGINE_H
#define PACKET_ENGINE_H

/* Warning: this file is auto-generated by cbindgen. Do not modify. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Maximum number of concurrent TCP flows tracked for reassembly.
 */
#define MAX_TCP_FLOWS 1024

/**
 * Maximum bytes buffered per TCP flow for reassembly.
 */
#define MAX_FLOW_BUFFER_BYTES 16384

/**
 * Flow timeout in seconds.
 */
#define FLOW_TIMEOUT_SECS 10

/**
 * Batch insert threshold.
 */
#define BATCH_INSERT_SIZE 50

/**
 * Batch flush interval in milliseconds.
 */
#define BATCH_FLUSH_INTERVAL_MS 500

/**
 * DNS standard port
 */
#define DNS_PORT 53

/**
 * HTTPS standard port
 */
#define HTTPS_PORT 443

/**
 * Maximum DNS query name length (per RFC 1035)
 */
#define MAX_DNS_NAME_LENGTH 253

/**
 * DNS header size in bytes
 */
#define DNS_HEADER_SIZE 12

/**
 * Maximum entries in DNS/IP correlator
 */
#define MAX_CORRELATOR_ENTRIES 4096

/**
 * DNS/IP correlation TTL in seconds
 */
#define CORRELATOR_TTL_SECS 300

/**
 * The main packet processing engine.
 *
 * Owns all mutable state and is NOT thread-safe (no need —
 * the Network Extension packet loop is single-threaded).
 */
typedef struct PacketEngine PacketEngine;

/**
 * Stats struct returned to Swift.
 */
typedef struct EngineStatsFFI {
    uint64_t packets_processed;
    uint64_t dns_domains_found;
    uint64_t sni_domains_found;
    uint64_t packets_skipped;
    uint64_t active_tcp_flows;
    uint64_t reassembly_memory_bytes;
    uint64_t ech_configs_stripped;
    uint64_t ech_connections_detected;
    uint64_t ech_resolved_via_dns;
    uint64_t ech_unresolved;
} EngineStatsFFI;

/**
 * Threat statistics returned to Swift.
 */
typedef struct ThreatStatsFFI {
    uint64_t threats_blocked;
    uint64_t threats_allowed;
    uint64_t feed_domain_count;
    uint64_t feeds_loaded;
} ThreatStatsFFI;

struct PacketEngine *packet_engine_init(const char *db_path);

void packet_engine_destroy(struct PacketEngine *engine);

int packet_engine_process(struct PacketEngine *engine,
                          const uint8_t *packet_data,
                          uintptr_t packet_len,
                          uint8_t *out_buf,
                          uintptr_t out_capacity,
                          uintptr_t *out_len);

int packet_engine_process_batch(struct PacketEngine *engine,
                                const uint8_t *const *packets,
                                const uintptr_t *lengths,
                                uintptr_t count);

int packet_engine_flush(struct PacketEngine *engine);

int packet_engine_set_noise_filter(struct PacketEngine *engine, bool enabled);

int packet_engine_set_ech_downgrade(struct PacketEngine *engine, bool enabled);

struct EngineStatsFFI packet_engine_get_stats(const struct PacketEngine *engine);

/**
 * Load a threat feed from hosts-format data.
 *
 * `data` and `feed_name` must be valid, non-null UTF-8 C strings.
 *
 * Returns `0` on success, `-1` on error.
 */
int packet_engine_load_threat_feed(struct PacketEngine *engine,
                                   const char *data,
                                   const char *feed_name);

/**
 * Add a domain to the user allowlist.
 *
 * Returns `0` on success, `-1` on error.
 */
int packet_engine_add_allowlist(struct PacketEngine *engine, const char *domain);

/**
 * Remove a domain from the user allowlist.
 *
 * Returns `0` on success, `-1` on error.
 */
int packet_engine_remove_allowlist(struct PacketEngine *engine, const char *domain);

/**
 * Get threat detection statistics.
 *
 * Returns a zeroed struct if the engine pointer is null.
 */
struct ThreatStatsFFI packet_engine_get_threat_stats(const struct PacketEngine *engine);

char *packet_engine_last_error(void);

void packet_engine_free_string(char *s);

#endif /* PACKET_ENGINE_H */
